name: Example App CI

on:
  pull_request:
    paths:
      - 'example/**'
      - '.github/workflows/example_app_ci.yml'

      # --- Shared paths for BOTH workflows ---
      - 'package.json'
      - 'yarn.lock'
      - '.eslintrc.js'
      - '.prettierrc.json'
      - 'tsconfig.base.json'
  push:
    branches:
      - main
    paths:
      - 'example/**'
      - '.github/workflows/example-app-ci.yml'

      # --- Shared paths for BOTH workflows ---
      - 'package.json'
      - 'yarn.lock'
      - '.eslintrc.js'
      - '.prettierrc.json'
      - 'tsconfig.base.json'

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install Yarn
        run: npm install -g yarn

      - name: ğŸŒ¿ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: ğŸ“¦ Install root dependencies
        run: yarn install --frozen-lockfile

      - name: ğŸ“¦ Install example dependencies (and build SDK)
        run: yarn install --frozen-lockfile
        working-directory: ./example

      - name: ğŸ¤“ Run ESLint
        run: yarn lint
        working-directory: ./example

      - name: âœ¨ Run Prettier check
        run: yarn prettier:check
        working-directory: ./example

      - name: ğŸ” Run TypeScript check
        run: yarn ts:check
        working-directory: ./example
